#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          rServo,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          lServo,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     susan,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftR,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     liftL,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    door,                 tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    servoL,               tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    servoR,               tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
int leftVal;
int rightVal;
int threshold=25;
int modifier=1;
float stoppingTime=1;
bool justStopped=false;
int timeAfter;
bool isPositive;
bool doorDown = true;
bool justStarted=true;

task main()
{
	while(true)
		{


		getJoystickSettings(joystick);

		if(joy1Btn(2))
		{
			if(modifier==1)
				modifier=2;

			else modifier=1;
		}

		if(abs(joystick.joy1_y1)>threshold)
			rightVal=-joystick.joy1_y1/modifier;

		else rightVal=0;

		if(abs(joystick.joy1_y2)>threshold)
			leftVal=-joystick.joy1_y2/modifier;

		else leftVal=0;

		motor[left]=leftVal;
		motor[right]=rightVal;
		if(joy1Btn(7))
			motor[liftL]=75;

		else if(joy1Btn(5))
			motor[liftL]=-50;

		else if(joy1Btn(2))
			motor[liftL]=-50;
		else if(joy1Btn(4))
			motor[liftL]=50;
		else motor[liftL]=0;
		if(joy1Btn(8)){
			motor[liftR]=75;
		}
		else if(joy1Btn(6)){
			motor[liftR]=-50;
		}
		else if(joy1Btn(2))
			motor[liftR]=-50;
		else if(joy1Btn(4))
			motor[liftR]=50;
		else motor[liftR]=0;
		if(joy1Btn(1)){
			servo[servoR]=256;
			servo[servoL]=10;
		}
		else if(joy1Btn(3)){
			servo[servoR]=128;
			servo[servoL]=100;
		}

		//arm, lazy susan and flag raiser
		if(joy2Btn(2))
		{
			justStopped=false;
			motor[arm]=40;
			isPositive=true;
		}

		else if (joy2Btn(4))
		{
			justStopped=false;
			//if(a == 1)
				motor[arm]=-40;
				isPositive=false;

			//if(a == -1)
					//motor[flag]=-100;
		}

		else if(justStarted){
			motor[arm]=0;
		}
		else{
		if(!justStopped){
			justStopped=true;
			ClearTimer(T1);
		}
			timeAfter=T1;
			if(timeAfter>stoppingTime*1000)
				timeAfter=stoppingTime*1000;
		if(isPositive)
			modifier=1;
		else modifier=-1;
		motor[arm]=40*modifier*cos((float)(timeAfter/1000.0)*(0.5*PI/stoppingTime));


		motor[arm] = 0;

		}

		if(joy2Btn(7))
			motor[susan]=50;

		else if(joy2Btn(8))
			motor[susan]=-50;

		else motor[susan]=0;


		if(joy2Btn(5))
			motor[flag]=100;

		else if (joy2Btn(6))
				motor[flag]=-100;

		else if(joy2Btn(1))
			motor[flag]=10;

		else if (joy2Btn(3))
				motor[flag]=-10;

		else motor[flag]=0;

		if(joy2Btn(12))
		{
				servo[door] = 20;
		}

		else if(joy2Btn(11))
		{
				servo[door] = 150;
		}

	}

}
